terraform_state_bucket = "my-terraform-state-kafka-eks-12345"
dynamodb_table         = "terraform-locks"
aws_region             = "us-east-1"
cluster_name           = "kafka-eks"
node_instance_type     = "m5.large"
kafka_deployment_type  = "statefulset"